const $=s=>document.querySelector(s);let workout=[],steps=[],idx=0,timer=null,remaining=0,total=0,running=false,deferredPrompt=null;
const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function duration(v,u){v=+v;return /min/i.test(u)?v*60:v}
function parseLine(line,n){let raw=line.trim();if(!raw)return null;let stamps=raw.match(/\[?(\d{1,2}:\d{2})(?::\d{2})?\s*[-–]\s*(\d{1,2}:\d{2})(?::\d{2})?\]?/);raw=raw.replace(/\[?\d{1,2}:\d{2}(?::\d{2})?\s*[-–]\s*\d{1,2}:\d{2}(?::\d{2})?\]?/,'').trim();let name=(raw.split(/[:,-]/)[0]||`Exercise ${n}`).trim();let rest=+(raw.match(/rest\s*(?:for\s*)?(\d+)\s*(sec|second|min|minute)/i)||[])[1]||15;let ru=(raw.match(/rest\s*(?:for\s*)?\d+\s*(sec|second|min|minute)/i)||[])[1]||'sec';rest=duration(rest,ru);let sets=+(raw.match(/(?:x|×)\s*(\d+)\s*(?:sets?)?|(?:sets?\s*[:=]?\s*|,\s*)(\d+)\s*sets?/i)||[]).slice(1).find(Boolean)||1;let tm=raw.match(/(\d+)\s*(sec(?:ond)?s?|min(?:ute)?s?)/i);let reps=raw.match(/(\d+)\s*(reps?|times?)/i);let type=tm?'time':'count';let amount=tm?duration(tm[1],tm[2]):reps?+reps[1]:null;if(!amount)return null;return{name,sets,rest,type,amount,start:stamps?.[1]||null,stop:stamps?.[2]||null}}
function build(){workout=$('#input').value.split(/\n|;/).map(parseLine).filter(Boolean);steps=[];workout.forEach(e=>{for(let s=1;s<=e.sets;s++){steps.push({...e,set:s,kind:'work'});if(e.rest&&!(s===e.sets&&e===workout.at(-1)))steps.push({kind:'rest',amount:e.rest,nextName:s<e.sets?e.name:(workout[workout.indexOf(e)+1]?.name||'Finished')})}});render();idx=0;$('#coach').classList.toggle('hidden',!steps.length);showReady()}
function render(){let workSecs=workout.filter(x=>x.type==='time').reduce((a,x)=>a+x.amount*x.sets,0),restSecs=workout.reduce((a,x,i)=>a+x.rest*(x.sets-(i===workout.length-1?1:0)),0);$('#summary').textContent=`${workout.length} exercises • ${workout.reduce((a,x)=>a+x.sets,0)} sets • timed work ${fmt(workSecs)} • planned rest ${fmt(Math.max(0,restSecs))}`;$('#plan').innerHTML=workout.map((e,i)=>`<li data-e="${i}"><b>${e.name}</b> — ${e.sets} set${e.sets>1?'s':''} × ${e.type==='time'?fmt(e.amount):e.amount+' reps'}, rest ${fmt(e.rest)}${e.start?` • ${e.start}–${e.stop}`:''}</li>`).join('')}
function beep(freq=880,len=.18){let A=window.AudioContext||window.webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;o.connect(g);g.connect(a.destination);g.gain.setValueAtTime(.2,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+len);o.start();o.stop(a.currentTime+len)}
function say(text){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.rate=.95;speechSynthesis.speak(u)}
function showReady(){clearInterval(timer);running=false;if(!steps.length)return;let s=steps[idx]||{};$('#phase').textContent='Ready';$('#current').textContent=s.kind==='work'?s.name:'Rest';$('#timer').textContent=s.kind==='work'&&s.type==='count'?`${s.amount} reps`:fmt(s.amount||0);$('#detail').textContent=s.kind==='work'?`Set ${s.set} of ${s.sets}`:`Next: ${s.nextName}`;$('#done').classList.toggle('hidden',!(s.kind==='work'&&s.type==='count'));highlight(s)}
function highlight(s){document.querySelectorAll('li').forEach(x=>x.classList.remove('active'));if(s.name){let i=workout.findIndex(x=>x.name===s.name);document.querySelector(`[data-e="${i}"]`)?.classList.add('active')}}
function begin(){if(idx>=steps.length)return finish();let s=steps[idx];running=true;beep(s.kind==='work'?1046:620);if(s.kind==='work'){say(`Start ${s.name}. Set ${s.set} of ${s.sets}`);$('#phase').textContent='Work';$('#current').textContent=s.name;$('#detail').textContent=`Set ${s.set} of ${s.sets}`;highlight(s);if(s.type==='count'){remaining=0;total=0;$('#timer').textContent=`${s.amount} reps`;$('#done').classList.remove('hidden');return}}else{say(`Rest for ${s.amount} seconds. Next, ${s.nextName}`);$('#phase').textContent='Rest';$('#current').textContent='Recover';$('#detail').textContent=`Next: ${s.nextName}`;$('#done').classList.add('hidden')}remaining=s.amount;total=s.amount;tick();clearInterval(timer);timer=setInterval(tick,1000)}
function tick(){let s=steps[idx];$('#timer').textContent=fmt(Math.max(0,remaining));$('#bar').style.width=`${total?100*(total-remaining)/total:0}%`;if(s.kind==='rest'&&[10,5,3,2,1].includes(remaining))say(remaining===10?'Ten seconds':String(remaining));if(remaining--<=0){clearInterval(timer);beep(330,.35);say(s.kind==='work'?'Stop':'Rest complete');setTimeout(next,450)}}
function next(){clearInterval(timer);idx++;if(idx>=steps.length)return finish();begin()}
function finish(){clearInterval(timer);running=false;$('#phase').textContent='Complete';$('#current').textContent='Great work!';$('#timer').textContent='✓';$('#detail').textContent='Workout completed';$('#bar').style.width='100%';say('Workout complete. Great work!')}
$('#parse').onclick=build;$('#demo').onclick=()=>{$('#input').value='Jumping Jacks: 30 sec x 2, rest 15 sec\nPush-ups: 12 reps, 3 sets, rest 30 sec\nPlank: 45 sec x 2, rest 20 sec';build()};$('#start').onclick=()=>{if(!steps.length)build();if(!running)begin()};$('#done').onclick=()=>{beep(330,.35);say('Set complete');next()};$('#pause').onclick=()=>{if(running){clearInterval(timer);running=false;$('#pause').textContent='Resume';speechSynthesis.cancel()}else{$('#pause').textContent='Pause';begin()}};$('#skip').onclick=next;$('#reset').onclick=()=>{idx=0;$('#pause').textContent='Pause';showReady()};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#install').classList.remove('hidden')});$('#install').onclick=async()=>{deferredPrompt?.prompt();deferredPrompt=null;$('#install').classList.add('hidden')};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');build();